# Generated by Django 6.0.7 on 2026-07-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("registration_number", models.CharField(max_length=20, unique=True)),
                ("vehicle_name", models.CharField(max_length=100)),
                ("vehicle_type", models.CharField(max_length=50)),
                ("max_load_capacity", models.FloatField()),
                ("odometer", models.FloatField(default=0)),
                (
                    "acquisition_cost",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("ON_TRIP", "On Trip"),
                            ("IN_SHOP", "In Shop"),
                            ("RETIRED", "Retired"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
