# Generated by Django 6.0.7 on 2026-07-12 06:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="current_location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="fuel_type",
            field=models.CharField(
                choices=[
                    ("PETROL", "Petrol"),
                    ("DIESEL", "Diesel"),
                    ("CNG", "CNG"),
                    ("EV", "Electric"),
                ],
                default="PETROL",
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vehicle",
            name="last_service_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="max_load_capacity",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="odometer",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="vehicle_type",
            field=models.CharField(
                choices=[
                    ("TRUCK", "Truck"),
                    ("VAN", "Van"),
                    ("BUS", "Bus"),
                    ("CAR", "Car"),
                ],
                max_length=20,
            ),
        ),
    ]
