# Generated by Django 6.0.7 on 2026-07-12 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("drivers", "0001_initial"),
        ("vehicles", "0002_vehicle_created_at_vehicle_current_location_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="driver",
            old_name="contact_number",
            new_name="phone_number",
        ),
        migrations.AddField(
            model_name="driver",
            name="assigned_vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_drivers",
                to="vehicles.vehicle",
            ),
        ),
        migrations.AddField(
            model_name="driver",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
