# Generated by Django 6.0.7 on 2026-07-12 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="fuel_consumed",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
