# Generated by Django 6.0.7 on 2026-07-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_trip_fuel_consumed"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="actual_distance",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cargo_weight",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="trip",
            name="fuel_consumed",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="trip",
            name="planned_distance",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
