# Generated by Django 6.0.7 on 2026-07-12 05:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("vehicles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_type",
                    models.CharField(
                        choices=[
                            ("FUEL", "Fuel"),
                            ("MAINTENANCE", "Maintenance"),
                            ("TOLL", "Toll"),
                            ("INSURANCE", "Insurance"),
                            ("OTHER", "Other"),
                        ],
                        max_length=30,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("expense_date", models.DateField()),
                ("remarks", models.TextField(blank=True)),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expenses",
                        to="vehicles.vehicle",
                    ),
                ),
            ],
        ),
    ]
