# Generated by Django 6.0.7 on 2026-07-12 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
        ("trips", "0003_trip_updated_at_alter_trip_actual_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="expense",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="trips.trip",
            ),
        ),
    ]
