# Generated by Django 6.0.7 on 2026-07-12 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fuel", "0001_initial"),
        ("trips", "0003_trip_updated_at_alter_trip_actual_distance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fuellog",
            name="trip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fuel_logs",
                to="trips.trip",
            ),
        ),
        migrations.AlterField(
            model_name="fuellog",
            name="liters",
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name="fuellog",
            name="odometer",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
